def printManual():
	print "----------quadrotor simulator by YS KIM----------"
	print ""
	print "o : simulation stop"
	print "p : simulation play"
	print "---- camera control------------------------------"
	print "w : dolly in"
	print "s : dolly out"
	print "d : zoom in"
	print "a : zoom out"
	print "m : print manual"
	print "n : Increase delaay"
	print "b : Decrease delay"
	print "r : plot error(only can use after trajectory tracking Finish)"
	print "t : make JsonFile(only can use atter trajectory tracking Finish)"
	print "SHIFT + DRAG : translate camera"
	print "DRAG : rotate camera"
